# The following is an example from the Mandrillapp.com API Docs
try:
    mandrill_client = mandrill.Mandrill('YOUR_API_KEY')
    result = mandrill_client.users.info()
    '''
    {'backlog': 42,
     'created_at': '2013-01-01 15:30:27',
     'hourly_quota': 42,
     'public_id': 'aaabbbccc112233',
     'reputation': 42,
     'stats': {'all_time': {'clicks': 42,
                            'complaints': 42,
                            'hard_bounces': 42,
                            'opens': 42,
                            'rejects': 42,
                            'sent': 42,
                            'soft_bounces': 42,
                            'unique_clicks': 42,
                            'unique_opens': 42,
                            'unsubs': 42},
               'last_30_days': {'clicks': 42,
                                'complaints': 42,
                                'hard_bounces': 42,
                                'opens': 42,
                                'rejects': 42,
                                'sent': 42,
                                'soft_bounces': 42,
                                'unique_clicks': 42,
                                'unique_opens': 42,
                                'unsubs': 42},
               'last_60_days': {'clicks': 42,
                                'complaints': 42,
                                'hard_bounces': 42,
                                'opens': 42,
                                'rejects': 42,
                                'sent': 42,
                                'soft_bounces': 42,
                                'unique_clicks': 42,
                                'unique_opens': 42,
                                'unsubs': 42},
               'last_7_days': {'clicks': 42,
                               'complaints': 42,
                               'hard_bounces': 42,
                               'opens': 42,
                               'rejects': 42,
                               'sent': 42,
                               'soft_bounces': 42,
                               'unique_clicks': 42,
                               'unique_opens': 42,
                               'unsubs': 42},
               'last_90_days': {'clicks': 42,
                                'complaints': 42,
                                'hard_bounces': 42,
                                'opens': 42,
                                'rejects': 42,
                                'sent': 42,
                                'soft_bounces': 42,
                                'unique_clicks': 42,
                                'unique_opens': 42,
                                'unsubs': 42},
               'today': {'clicks': 42,
                         'complaints': 42,
                         'hard_bounces': 42,
                         'opens': 42,
                         'rejects': 42,
                         'sent': 42,
                         'soft_bounces': 42,
                         'unique_clicks': 42,
                         'unique_opens': 42,
                         'unsubs': 42}},
     'username': 'myusername'}
    '''

except mandrill.Error, e:
    # Mandrill errors are thrown as exceptions
    print 'A mandrill error occurred: %s - %s' % (e.__class__, e)
    # A mandrill error occurred: <class 'mandrill.InvalidKeyError'> - Invalid API key    
    raise